### ISSUE TITLE
Texture bugs on Light Bridge and some Light Fixtures

### ISSUE THREAD

**Issue by MichaelAquilina** [ValveSoftware/portal2#101]
I am currently running Kubuntu 13.10 64 bit with a GeForce GT555M (running on primus).

All other textures seem fine, it just seems to be these two.

<img src="https://dl.dropboxusercontent.com/u/824515/portal_texture2.png"/>
<img src="https://dl.dropboxusercontent.com/u/824515/portal_texture.png"/>

System Information:

```
Processor Information:
Vendor:  GenuineIntel
CPU Family:  0x6
CPU Model:  0x2a
CPU Stepping:  0x7
CPU Type:  0x0
Speed:  2001 Mhz
8 logical processors
4 physical processors
HyperThreading:  Supported
FCMOV:  Supported
SSE2:  Supported
SSE3:  Supported
SSSE3:  Supported
SSE4a:  Unsupported
SSE41:  Supported
SSE42:  Supported

Network Information:
Network Speed:  

Operating System Version:
Ubuntu 13.10 (64 bit)
Kernel Name:  Linux
Kernel Version:  3.11.0-17-generic
X Server Vendor:  The X.Org Foundation
X Server Release:  11405000
X Window Manager:  KWin
Steam Runtime Version:  steam-runtime-release_2014-02-05

Video Card:
Driver:  Intel Open Source Technology Center Mesa DRI Intel(R) Sandybridge Mobile x86/MMX/SSE2

Driver Version:  3.0 Mesa 10.2.0-devel
OpenGL Version: 3.0
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x10de
DeviceID:  0xdcd
Number of Monitors:  1
Number of Logical Video Cards:  2
Primary Display Resolution:  1920 x 1080
Desktop Resolution: 1920 x 1080
Primary Display Size: 20.91" x 11.73"  (23.94" diag)
                    53.1cm x 29.8cm  (60.8cm diag)
Primary VRAM Not Detected

Sound card:
Audio device: Intel CougarPoint HDMI

Memory:
RAM:  5883 Mb

Miscellaneous:
UI Language:  English
LANG:  en_GB.UTF-8
Microphone:  Not set
Total Hard Disk Space Available:  93795 Mb
Largest Free Hard Disk Block:  32280 Mb

Installed software:

Recent Failure Reports:
```

**Comment by timjp87** [comment]
What texture filtering mode in the advanced graphics settings do you use? Does changing the filtering mode or texture quality level affect this issue?

**Comment by MaartenBaert** [comment]
I had this too, solved it by switching to anisotropic instead of trilinear filtering. It still doesn't make sense though, trilinear shouldn't produce sharp transitions (only bilinear does that).

Here's a better screenshot (full 1080p, no scaling):
![sp_a2_column_blocker0000](https://f.cloud.github.com/assets/829608/2295731/27f8672c-a094-11e3-8c83-04d6154a81cd.jpg)

**Comment by MichaelAquilina** [comment]
My current setting is trilinear filtering like @MaartenBaert. Will check if changing to antisotropic works for me tomorrow.

**Comment by panzi** [comment]
I have this too. My system:

```
Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3c
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  3900 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    "Fedora release 20 (Heisenbug)" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.13.4-200.fc20.x86_64
    X Server Vendor:  Fedora Project
    X Server Release:  11404000
    X Window Manager:  KWin
    Steam Runtime Version:  steam-runtime-release_2014-02-05

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 760/PCIe/SSE2

    Driver Version:  4.4.0 NVIDIA 331.49
    OpenGL Version: 4.4
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x10de
    DeviceID:  0x1187
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 1080
    Primary Display Size: 20,08" x 11,30"  (23,03" diag)
                                            51,0cm x 28,7cm  (58,5cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 2048 MB
    Supported MSAA Modes:  2x 4x 8x 16x 

Sound card:
    Audio device: Realtek ALC1150

Memory:
    RAM:  15988 Mb

Miscellaneous:
    UI Language:  English
    LANG:  de_AT.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  914161 Mb
    Largest Free Hard Disk Block:  701980 Mb

Installed software:

Recent Failure Reports:

```

**Comment by panzi** [comment]
To clarify: I have the light bridge edge issues as well, not the thing with the lamps. The lamps are fine for me.

**Comment by timjp87** [comment]
@Panzi Could you provide  a screenshot and say what graphics settings you use? I have not noticed any texture bugs with NVIDIA. For some some texture filtering modes it is expected to have this kind of behaviour. You should be able to play with 8x MSAA und 16x Anisotropic Filtering which provides the best picture quality and does not show any artifacts.

**Comment by panzi** [comment]
@blackout24 I haven't had these settings changed. Changing them to what you suggested fixed it.

Here is a screenshot anyway:
![light bridge edge graphics error](http://cloud-2.steampowered.com/ugc/792936371075612624/0B4104952DFEDAF0F26DE438512962BB2667CFD4/)

And here the settings as they where:
![video settings](http://cloud-4.steampowered.com/ugc/792936371075605604/AA15565D7699A1D1D044C54AB34B59C128B6586D/)

But even then one can see little bulges where the breaks in the lines where, so maybe it's just masking the real problem?
![bulge in light bridge edge](http://cloud-2.steampowered.com/ugc/792936371075761964/00AF9F85F5B607B5816EDFDF68DFB04700A68E3B/)

**Comment by UnderwaterCowboy** [comment]
I'm having similar issues on Ubuntu 13.10 64-bit with an AMD 6870 GPU and 8120 CPU.
![screenshot from 2014-03-02 08 32 12](https://f.cloud.github.com/assets/6831575/2304396/e76fcc08-a21a-11e3-84a1-679592baf74d.png)

**Comment by mariodonofrio** [comment]
Trilinear wasn't being applied properly unless Aniso settings were 2x or greater. This should be fixed with the next build.

**Comment by davidw-valve** [comment]
This is fixed in the latest update.

**Comment by stevethepocket** [comment]
I just updated to the current version. The light fixtures still have the low-res pixel look, and the light bridges now look like this:

![sp_a2_bridge_intro0005](https://f.cloud.github.com/assets/3085348/2495263/75bf7a0a-b2ef-11e3-9b03-3c88187a2906.jpg)

Improved, but still not fixed. Requesting that this be re-opened. ATi Radeon 4850 with open-source driver, filtering set to trilinear.

**Comment by mariodonofrio** [comment]
This is a different issue to the original, and not one I'm able to repro - UnderwaterCowboy can you let me know what driver you're using please, and is it possible to try a newer one? steve - it may well be the opensource driver issue here. 
Also to eliminate mip-map generation can you also try mat_picmip 4 in the console (forces lower mip level), be interesting to see a screenshot with mat_showmiplevels 1 as well. Can't think it would be that if all other materials look okay. 
Am guessing all the filter/aniso settings make no difference either?
Lastly, try deleting glshaders.cfg & glbaseshaders.cfg and re-run...It might be slow to start up the first time and into the first map or so.
Thanks.

**Comment by stevethepocket** [comment]
OK, I decided to play around with the settings a bit. It seems that as I change from trilinear, to aniso 2x, to aniso 4x etc., the area where the light bridge looks correct extends further into the distance and there's less and less of the double-sized pixels in the fluorescent light props. I'm not sure what, if anything, that signifies.

**Comment by mariodonofrio** [comment]
Sounds like the mip-maps are bad in that case (or the driver is looking up garbage) since those aniso settings just push the distance at which lower level mips are used for polygons that are edge on. If that's the case, then mat_picmip 4 should show the bad texture up close since it forces the use of lower level mip-maps.

**Comment by stevethepocket** [comment]
Update: Finally got access to my Windows system back and decided to see how things look on that. Running the non-beta version, I got light bridges that looked correct other than sharp seams between mipmap levels...

![sp_a2_bridge_intro0000](https://cloud.githubusercontent.com/assets/3085348/2563253/00f2dc24-b878-11e3-9cce-63d55958f082.jpg)

...and after opting into the beta, those went away as well. So that's definitely something to do with AMD under Linux. @UnderwaterCowboy, are you using the open source driver or Catalyst? You and I seem to be the only ones with the vanishing bridge issue.

The wonky light fixtures, however, appear to be independent of the OS. This is what they look like in Windows with Trilinear filtering:

![sp_a2_bridge_intro0001](https://cloud.githubusercontent.com/assets/3085348/2563254/0296b53c-b878-11e3-948a-335af3f74e5a.jpg)

Again, Radeon HD 4850; in this case, Windows 7 x64 and version 8.961.0.0 of the driver according to my system info, whatever that means. (It's whatever Windows installed automatically or maybe what Windows Update upgraded me to. I've tried installing newer versions of Catalyst manually, and they always make my system unusable. But all my games run fine in full HD without it, so I don't mess with it anymore.)

**Comment by UnderwaterCowboy** [comment]
I apologize for the pate response. I'm using the open source driver as part
of the kernel included with Ubuntu 13.10.
