### ISSUE TITLE
Portal 2 does not launch (crashes immediately)

### ISSUE THREAD

**Issue by nottux** [ValveSoftware/portal2#298]
Testing with newly installed portal 2;
In first crash, terminal log ends up with missing GameInfo.txt file error
after copying gameinfo.txt file to GameInfo.txt, game does launch, intro and loding screen shows up but game menu does not launch
i have recorded terminal, dump folder and game simultaneously
in zip file: recorded screen video in mp4 format, cpuinfo, glxinfo, terminal dump, created files in  /tmp/dumps folder and steam system information exist
[portal2_launch_issue.zip](https://github.com/ValveSoftware/portal2/files/1802932/portal2_launch_issue.zip)

Video:
[![Video](https://img.youtube.com/vi/bAIU5AWqvP0/0.jpg)](https://www.youtube.com/watch?v=bAIU5AWqvP0)

Terminal dump:
```
[utku@utku2 Portal 2]$ LD_LIBRARY_PATH=bin ./portal2.sh -game portal2 
SDL video target is 'x11'
SDL video target is 'x11'

SDL failed to create GL compatibility profile (whichProfile=0!
SDL failed to create GL compatibility profile (whichProfile=0!

This system supports the OpenGL extension GL_EXT_framebuffer_object.
This system supports the OpenGL extension GL_EXT_framebuffer_blit.
This system supports the OpenGL extension GL_EXT_framebuffer_multisample.
This system DOES NOT support the OpenGL extension GL_APPLE_fence.
This system DOES NOT support the OpenGL extension GL_NV_fence.
This system supports the OpenGL extension GL_ARB_sync.
This system supports the OpenGL extension GL_EXT_draw_buffers2.
This system DOES NOT support the OpenGL extension GL_EXT_bindable_uniform.
This system DOES NOT support the OpenGL extension GL_APPLE_flush_buffer_range.
This system supports the OpenGL extension GL_ARB_map_buffer_range.
This system supports the OpenGL extension GL_ARB_vertex_buffer_object.
This system supports the OpenGL extension GL_ARB_occlusion_query.
This system DOES NOT support the OpenGL extension GL_APPLE_texture_range.
This system DOES NOT support the OpenGL extension GL_APPLE_client_storage.
This system DOES NOT support the OpenGL extension GL_ARB_uniform_buffer.
This system supports the OpenGL extension GL_ARB_vertex_array_bgra.
This system supports the OpenGL extension GL_EXT_vertex_array_bgra.
This system supports the OpenGL extension GL_ARB_framebuffer_object.
This system DOES NOT support the OpenGL extension GL_GREMEDY_string_marker.
This system supports the OpenGL extension GL_ARB_debug_output.
This system DOES NOT support the OpenGL extension GL_EXT_direct_state_access.
This system DOES NOT support the OpenGL extension GL_NV_bindless_texture.
This system DOES NOT support the OpenGL extension GL_AMD_pinned_memory.
This system supports the OpenGL extension GL_EXT_framebuffer_multisample_blit_scaled.
This system supports the OpenGL extension GL_EXT_texture_sRGB_decode.
This system DOES NOT support the OpenGL extension GL_NVX_gpu_memory_info.
This system DOES NOT support the OpenGL extension GL_ATI_meminfo.
This system supports the OpenGL extension GL_EXT_texture_compression_s3tc.
This system supports the OpenGL extension GL_EXT_texture_compression_dxt1.
This system supports the OpenGL extension GL_ANGLE_texture_compression_dxt3.
This system supports the OpenGL extension GL_ANGLE_texture_compression_dxt5.
This system DOES NOT support the OpenGL extension GLX_EXT_swap_control_tear.
Setup file 'GameInfo.txt' doesn't exist in subdirectory 'portal2'.
Check your -game parameter or VCONFIG setting.
Setup file 'GameInfo.txt' doesn't exist in subdirectory 'portal2'.
Check your -game parameter or VCONFIG setting.

[utku@utku2 Portal 2]$ LD_LIBRARY_PATH=bin ./portal2.sh -game portal2 
SDL video target is 'x11'
SDL video target is 'x11'

SDL failed to create GL compatibility profile (whichProfile=0!
SDL failed to create GL compatibility profile (whichProfile=0!

This system supports the OpenGL extension GL_EXT_framebuffer_object.
This system supports the OpenGL extension GL_EXT_framebuffer_blit.
This system supports the OpenGL extension GL_EXT_framebuffer_multisample.
This system DOES NOT support the OpenGL extension GL_APPLE_fence.
This system DOES NOT support the OpenGL extension GL_NV_fence.
This system supports the OpenGL extension GL_ARB_sync.
This system supports the OpenGL extension GL_EXT_draw_buffers2.
This system DOES NOT support the OpenGL extension GL_EXT_bindable_uniform.
This system DOES NOT support the OpenGL extension GL_APPLE_flush_buffer_range.
This system supports the OpenGL extension GL_ARB_map_buffer_range.
This system supports the OpenGL extension GL_ARB_vertex_buffer_object.
This system supports the OpenGL extension GL_ARB_occlusion_query.
This system DOES NOT support the OpenGL extension GL_APPLE_texture_range.
This system DOES NOT support the OpenGL extension GL_APPLE_client_storage.
This system DOES NOT support the OpenGL extension GL_ARB_uniform_buffer.
This system supports the OpenGL extension GL_ARB_vertex_array_bgra.
This system supports the OpenGL extension GL_EXT_vertex_array_bgra.
This system supports the OpenGL extension GL_ARB_framebuffer_object.
This system DOES NOT support the OpenGL extension GL_GREMEDY_string_marker.
This system supports the OpenGL extension GL_ARB_debug_output.
This system DOES NOT support the OpenGL extension GL_EXT_direct_state_access.
This system DOES NOT support the OpenGL extension GL_NV_bindless_texture.
This system DOES NOT support the OpenGL extension GL_AMD_pinned_memory.
This system supports the OpenGL extension GL_EXT_framebuffer_multisample_blit_scaled.
This system supports the OpenGL extension GL_EXT_texture_sRGB_decode.
This system DOES NOT support the OpenGL extension GL_NVX_gpu_memory_info.
This system DOES NOT support the OpenGL extension GL_ATI_meminfo.
This system supports the OpenGL extension GL_EXT_texture_compression_s3tc.
This system supports the OpenGL extension GL_EXT_texture_compression_dxt1.
This system supports the OpenGL extension GL_ANGLE_texture_compression_dxt3.
This system supports the OpenGL extension GL_ANGLE_texture_compression_dxt5.
This system DOES NOT support the OpenGL extension GLX_EXT_swap_control_tear.
Using breakpad crash handler
Setting breakpad minidump AppID = 620
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198301669039 [API loaded yes]
Steam_SetMinidumpSteamID:  Setting Steam ID:  76561198301669039
Did not detect any valid joysticks.
Did not detect any valid joysticks.

CSoundEmitterSystemBase::BaseInit:  Manifest 'scripts/game_sounds_manifest.txt' with bogus file type 'new_sound_scripts_must_go_below_here', expecting 'declare_file' or 'precache_file'
CSoundEmitterSystemBase::BaseInit:  Manifest 'scripts/game_sounds_manifest.txt' with bogus file type 'new_sound_scripts_must_go_below_here', expecting 'declare_file' or 'precache_file'

Convar r_flashlightscissor has conflicting FCVAR_CHEAT flags (child: no FCVAR_CHEAT, parent: has FCVAR_CHEAT, parent wins)
Convar r_flashlightscissor has conflicting FCVAR_CHEAT flags (child: no FCVAR_CHEAT, parent: has FCVAR_CHEAT, parent wins)

VerifyDefaultVideoConfig: The default video config for the machine has changed, updating the current config to match.
VerifyDefaultVideoConfig: The default video config for the machine has changed, updating the current config to match.


 ##### swap interval = 1     swap limit = 1 #####
Did not detect any valid joysticks.
Did not detect any valid joysticks.

Did not detect any valid joysticks.
Did not detect any valid joysticks.

Did not detect any valid joysticks.
Did not detect any valid joysticks.

Could not load program cache file glshaders.cfg
Could not load program cache file glshaders.cfg

Could not find user GL shader cache file
Could not find user GL shader cache file

CClientSteamContext logged on = 1
CClientSteamContext logged on = 1

Convar building_cubemaps has conflicting FCVAR_CHEAT flags (child: has FCVAR_CHEAT, parent: no FCVAR_CHEAT, parent wins)
Convar building_cubemaps has conflicting FCVAR_CHEAT flags (child: has FCVAR_CHEAT, parent: no FCVAR_CHEAT, parent wins)

Game.dll loaded for "Half-Life 2"
Game.dll loaded for "Half-Life 2"

crash_20180312161303_1.dmp[8581]: Uploading dump (out-of-process)
/tmp/dumps/crash_20180312161303_1.dmp
crash_20180312161303_1.dmp[8581]: Finished uploading minidump (out-of-process): success = yes
crash_20180312161303_1.dmp[8581]: response: CrashID=bp-bbae0319-ac10-4a26-8209-a84c72180312
crash_20180312161303_1.dmp[8581]: file ''/tmp/dumps/crash_20180312161303_1.dmp'', upload yes: ''CrashID=bp-bbae0319-ac10-4a26-8209-a84c72180312''
./portal2.sh: satır 51:  8564 Parçalama arızası    (çekirdek döküldü)${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"
```
/tmp/dumps/utku_log.txt
```
Mon Mar 12 13:13:51 2018 GMT: file ''/tmp/dumps/crash_20180312161303_1.dmp'', upload yes: ''CrashID=bp-bbae0319-ac10-4a26-8209-a84c72180312''
```
[/tmp/dumps/crash_20180312161303_1.dmp](https://github.com/ValveSoftware/portal2/files/1802954/crash_20180312161303_1.dmp.txt)

uname -a
```
[utku@utku2 ~]$ uname -a
Linux utku2 4.15.7-1-ARCH #1 SMP PREEMPT Wed Feb 28 19:01:57 UTC 2018 x86_64 GNU/Linux
```
steam system information:
```
Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Laptop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:  Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz
    CPU Family:  0x6
    CPU Model:  0x3d
    CPU Stepping:  0x4
    CPU Type:  0x0
    Speed:  1900 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    Linux 4.x (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.15.7-1-ARCH
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11906000
    X Window Manager:  Xfwm4
    Steam Runtime Version:  <Runtime disabled>

Video Card:
    Driver:  Intel Open Source Technology Center Mesa DRI Intel(R) HD Graphics 5500 (Broadwell GT2) x86/MMX/SSE2
    Driver Version:  3.0 Mesa 17.3.6
    OpenGL Version: 3.0
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x8086
    DeviceID:  0x1616
    Revision Not Detected
    Number of Monitors:  2
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1360 x 768
    Desktop Resolution: 2726 x 768
    Primary Display Size: 15,98" x 9,02" (18,35" diag)
                                            40,6cm x 22,9cm (46,6cm diag)
    Primary VRAM Not Detected

Sound card:
    Audio device: Intel Broadwell HDMI

Memory:
    RAM:  3863 Mb

Miscellaneous:
    UI Language:  English
    LANG:  tr_TR.UTF-8
    Total Hard Disk Space Available:  335332 Mb
    Largest Free Hard Disk Block:  159975 Mb
    VR Headset: None detected

Recent Failure Reports:

```

[$glxinfo](https://github.com/ValveSoftware/portal2/files/1802967/glxinfo.txt)

[/proc/cpuinfo](https://github.com/ValveSoftware/portal2/files/1802971/cpuinfo.txt)

**Comment by kisak-valve** [comment]
For reference, the attached minidump is a SIGSEGV in client.so (part of Portal 2). It looks like a null pointer.

**Comment by nottux** [comment]
i have tried to rename `SAVE` folder in `/home/utku/.local/share/Steam/steamapps/common/Portal 2/portal2/` and `620` folder at `/home/utku/.local/share/Steam/userdata/341403311/` but it didn't changed anything.
save files are in the archive:
[portal2_save_files.zip](https://github.com/ValveSoftware/portal2/files/1819629/portal2_save_files.zip)

**Comment by nottux** [comment]
Should i keep `GameInfo.txt` file even it shouldn't be there?

**Comment by nottux** [comment]
Extra information that i forget to mention:

[![Video](https://img.youtube.com/vi/F60zYFD_ZTc/0.jpg)](https://www.youtube.com/watch?v=F60zYFD_ZTc)
Time that this video recorded/published game was working fine on:
clearlinux with intel core i3-380m CPU / No dedicated GPU / Flatpak version of steam ( all software was up-to-date to its time) / video recorded with this setup

Antergos with intel core i3-380m CPU / No dedicated GPU / Antergos repository version ( all software was up-to-date to its time )

After certain date game never launched with:
clearlinux with intel core i3-380m CPU / No dedicated GPU / Flatpak version of steam ( all software was up-to-date to its time)

Antergos with intel core i3-380m CPU / No dedicated GPU / Antergos repository version ( all software was up-to-date to its time )

Antergos with Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz / No dedicated GPU / Antergos repository version ( all software was up-to-date to its time )

**Comment by Tarhana-is-best-soup** [comment]
I have the same problem and same terminal dump except the last bit about joysticks. I know it is kinda late but, have you found any solution to it?

**Comment by nottux** [comment]
I guess its a library problem,
if you using an arch based distro have you tried to launch ```steam-runtime``` and not ```steam-native``` 
I don't know how to do this on other distros
```steam-runtime``` is launches steam with standard  libraries , ```steam-native``` launches steam with system libraries that kept updated , launching ```steam-runtime``` can fix your problem

**Comment by tuxutku** [comment]
It doesn't working on me even activating steam runtime with ``STEAM_RUNTIME=1 steam``
since i am getting different error massage with different hardware on different build etc...
i will open  a new issue

**Comment by nottux** [comment]
it can also be the issue here:
https://steamcommunity.com/app/221910/discussions/0/517141624283080668/

**Comment by kisak-valve** [comment]
Hello @tuxutku, no, that issue was resolved: https://github.com/ValveSoftware/portal2/issues/248#issuecomment-318195320

**Comment by nottux** [comment]
i have tested with my new system whitch has
AMD RX 540 graphics and AMD A10-9620P CPU
DRI_PRIME=1 doesn't resolve anything too
Tested on Linux Mint 19 and Manjaro with STEAM_RUNTİME=1 , STEAM_RUNTİME=0 , flatpak version and native version
i am sure that the game files were intact because i3-5000 series cpu with no dedicated graphics on Linux Mint 19 works fine

**Comment by kisak-valve** [comment]
Hello @tuxutku, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
