### ISSUE TITLE
LD_LIBRARY_PATH truncated when calling Puzzle Editor utilities

### ISSUE THREAD

**Issue by landswellsong** [ValveSoftware/portal2#335]
When trying to compile the map in the Puzzle Editor, VBSP fails to start up:

```
VBSP failed.

ERROR: ld.so: object '/home/elfy/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
/home/elfy/.local/share/Steam/steamapps/common/Portal 2/bin/vbsp_linux: error while loading shared libraries: libuuid.so.1: cannot open shared object file: No such file or directory
```

The `libuuid.so.1` is indeed missing from the Portal 2's `bin` directory, so the operation must have relied on the host runtime, which is probably the case in ValveSoftware/portal2#235 as the reporter had a 64-bit host. The library in question can be found within steam's own runtime shipped under `~/.local/Steam`, copying or symlinking into Portal 2's `bin` directory remedies the problem.

Adding the library to the Portal 2's installation or making sure it uses the Steam runtime would fix this issue for new users.

System info just in case: https://gist.github.com/ohhai/e4bc5345be924f36c3241226795e5bc4

**Comment by landswellsong** [comment]
@smcv spot on, I checked the length and it's 254 characters (i.e. 255 with zero terminator).

**Comment by smcv** [comment]
Please could you retitle to "LD_LIBRARY_PATH truncated, preventing Puzzle Editor from compiling maps" or something like that? Based on what we've learned, the original title is misleading.

**Comment by kisak-valve** [comment]
Hello @landswellsong, there was some fixes near this in the [2021-02-18](https://store.steampowered.com/oldnews/81067) Portal 2 update and I'm no longer able to reproduce this issue on a Gentoo test box. Please retest this issue.

**Comment by landswellsong** [comment]
Hello @kisak-valve, thanks for the heads up.
I re-tested the issue and here's what I'm getting:
1. The user-facing issue disappeared, i.e. I can launch the editor and rebuild maps without maps.
2. The `LD_LIBRARY_PATH` variable is still truncated as before.
3. Upon closer examination this is because the `libuuidgen.so.1` dependency is dropped (the `ldd` output follows):
```
ERROR: ld.so: object '/home/elfy/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
        linux-gate.so.1 (0xf7fcd000)
        /home/elfy/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so (0xf7f86000)
        libtcmalloc_minimal.so.4 => /home/elfy/.local/share/Steam/steamapps/common/Portal 2/bin/libtcmalloc_minimal.so.4 (0xf7f44000)
        libtier0.so => /home/elfy/.local/share/Steam/steamapps/common/Portal 2/bin/libtier0.so (0xf7f0f000)
        libvstdlib.so => /home/elfy/.local/share/Steam/steamapps/common/Portal 2/bin/libvstdlib.so (0xf7ec1000)
        libm.so.6 => /lib/libm.so.6 (0xf7dcb000)
        libdl.so.2 => /lib/libdl.so.2 (0xf7dc5000)
        libstdc++.so.6 => /usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/32/libstdc++.so.6 (0xf7b3d000)
        libpthread.so.0 => /lib/libpthread.so.0 (0xf7b1c000)
        libc.so.6 => /lib/libc.so.6 (0xf792e000)
        librt.so.1 => /lib/librt.so.1 (0xf7921000)
        /lib/ld-linux.so.2 (0xf7fcf000)
        libGL.so.1 => /usr/lib/libGL.so.1 (0xf78b5000)
        libgcc_s.so.1 => /usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/32/libgcc_s.so.1 (0xf7897000)
        libGLdispatch.so.0 => /usr/lib/libGLdispatch.so.0 (0xf781a000)
        libGLX.so.0 => /usr/lib/libGLX.so.0 (0xf77de000)
        libX11.so.6 => /usr/lib/libX11.so.6 (0xf7689000)
        libxcb.so.1 => /usr/lib/libxcb.so.1 (0xf765b000)
        libXau.so.6 => /usr/lib/libXau.so.6 (0xf7655000)
        libXdmcp.so.6 => /usr/lib/libXdmcp.so.6 (0xf764d000)
``` 


PS: now Portal has an icon ^_^

**Comment by smcv** [comment]
> The LD_LIBRARY_PATH variable is still truncated as before

With my Steam Runtime hat on: this is going to cause problems for someone sooner or later (our `LD_LIBRARY_PATH` is increasingly long, but everything in there is in there for a reason), and it would be great if Portal 2 could fix the truncation.

**Comment by misyltoad** [comment]
This should be fixed now.

**Comment by landswellsong** [comment]
@Joshua-Ashton still seeing it, Portal 2 build 6318595, do I need to update something else too, like Steam itself?

**Comment by misyltoad** [comment]
Nope, it should just work now. Hmm

**Comment by landswellsong** [comment]
@Joshua-Ashton ok I will re-test in the evening. Are we talking about the truncation thing?

**Comment by smcv** [comment]
If you need to confirm this on a test system, you can make the `LD_LIBRARY_PATH` artificially longer by running Steam with something like:

```
LD_LIBRARY_PATH="/nonexistent/012345689012345689012345689:$LD_LIBRARY_PATH" steam
```

Add more junk path entries as necessary. The Steam Runtime infrastructure should pass them through unchanged; if there's a fixed-length buffer involved, they'll eventually push the necessary path entries off the other end of the buffer.
