### ISSUE TITLE
New update crashes on Linux

### ISSUE THREAD

**Issue by ProkopRandacek** [ValveSoftware/portal2#353]
The new update for Portal 2 crashes on start. When I switch to previous release branch, the games runs normal.

steam info: https://pastebin.com/i0Mgjp1p
full steam log: https://pastebin.com/SBPkLfxH

I believe this error is the same as
https://github.com/ValveSoftware/csgo-osx-linux/issues/2651
https://github.com/ValveSoftware/csgo-osx-linux/issues/2659
error:
```
/home/prokop/.local/share/Steam/steamapps/common/Portal 2/portal2.sh: line 51: 33317 Segmentation fault      (core dumped) ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"
```
When I try to use gdb:
```
gdb: /home/prokop/.local/share/Steam/ubuntu12_32/steam-runtime/pinned_libs_64/libcurl.so.4: version `CURL_OPENSSL_4' not found (required by /usr/lib/libdebuginfod.so.1)
```

**Comment by misyltoad** [comment]
Thanks for reporting, there was a problem where some binaries were not updated correctly in the last update that is likely the cause. It should be fixed in the next update which should hopefully be today.

**Comment by misyltoad** [comment]
Should be fixed now!

**Comment by ProkopRandacek** [comment]
I downloaded the patch and the game still crashes for me.

full steam log: https://pastebin.com/LrpGLALB
error line: 
```
/home/prokop/.local/share/Steam/steamapps/common/Portal 2/portal2.sh: line 51: 497720 Segmentation fault      (core dumped) ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"
```
gdb:
```
gdb: /home/prokop/.local/share/Steam/ubuntu12_32/steam-runtime/pinned_libs_64/libcurl.so.4: version `CURL_OPENSSL_4' not found (required by /usr/lib/libdebuginfod.so.1)
```
branch `previous_release` still works
Is there any other info I can provide?

**Comment by misyltoad** [comment]
Does it work if you force the game to run under the "Steam Linux Runtime" compatibility tool?

**Comment by ProkopRandacek** [comment]
First I got this error:
![image](https://user-images.githubusercontent.com/40907224/118996749-6b310e80-b988-11eb-8def-d32d5d1931d1.png)
Then I reinstalled steam and redownloaded portal 2. That fixed it. I think I broke the compatibility things and probably broke it. Now everything works :D

**Comment by calexil** [comment]
this is still broken btw @kisak-valve 

Linux mint 20.3 mate
kernel 5.15.0-67-generic
Mesa 23.0.0 - kisak-mesa PPA

It just instantly crashes.

previous_release works

**Comment by kisak-valve** [comment]
Hello @calexil, `this is still broken` and `previous_release works` are contradictory. It can't both be broken for ~22 months and also be working in the previous release. Please open a new issue report.

**Comment by calexil** [comment]
dont know what to say bub, the default branch crashes immediately and the previous_release does not. its that simple
