### ISSUE TITLE
Segmentation fault at level change.

### ISSUE THREAD

**Issue by Lampus** [ValveSoftware/portal2#54]
Portal 2 Beta crashed with segmentation fault error on each second stage load.
For example:
1) Complete some level.
2) Go to elevator.
3) Save the game (F6)
4) Wait loading of the next level (without any errors)
5) Complete the level.
6) Go to elevator.
7) Save the game (F6)
8) Wait loading of the next level...
9) Game crashed on the level load screen with segmenation fault in function IDirect3DDevice9::DrawIndexedPrimitive(_D3DPRIMITIVETYPE, int, unsigned int, unsigned int, unsigned int, unsigned int) (libtogl.so).

Now I can restart game from save, complete next game level, but on the next loading screen game will crash again.

My system information:

```
Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x2a
    CPU Stepping:  0x7
    CPU Type:  0x0
    Speed:  3800 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Linux 3.10 (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.13.5-1-ARCH
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11500000
    X Window Manager:  KWin
    Steam Runtime Version:  steam-runtime-release_2014-02-05

Video Card:
    Driver:  NVIDIA Corporation GeForce 9600 GT/PCIe/SSE2

    Driver Version:  3.3.0 NVIDIA 331.38
    OpenGL Version: 3.3
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 59 Hz
    VendorID:  0x10de
    DeviceID:  0x622
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1680 x 1050
    Desktop Resolution: 1680 x 1050
    Primary Display Size: 18.62" x 11.65"  (21.93" diag)
                                            47.3cm x 29.6cm  (55.7cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 512 MB
    Supported MSAA Modes:  2x 4x 8x 16x 

Sound card:
    Audio device: Realtek ALC889

Memory:
    RAM:  3915 Mb

Miscellaneous:
    UI Language:  English
    LANG:  ru_RU.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  151061 Mb
    Largest Free Hard Disk Block:  29785 Mb

Installed software:

Recent Failure Reports:
```

Steam and GDB output:

```
[lampus@lampus-desktop ~]$ GAME_DEBUGGER="gdb" steam
Running Steam on arch  64-bit
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(1393366296_client)
Installing breakpad exception handler for appid(steam)/version(1393366296_client)

(steam:4648): Gtk-WARNING **: Загружаемый модуль тем не найден в module_path: «oxygen-gtk»,

(steam:4648): Gtk-WARNING **: Загружаемый модуль тем не найден в module_path: «oxygen-gtk»,
Installing breakpad exception handler for appid(steam)/version(1393366296_client)
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
[0226/165948:ERROR:object_proxy.cc(239)] Failed to call method: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.NetworkManager was not provided by any .service files
[0226/165948:WARNING:proxy_service.cc(958)] PAC support disabled because there is no system implementation
Installing breakpad exception handler for appid(steam)/version(1393366296_client)
Installing breakpad exception handler for appid(steam)/version(1393366296_client)

** (steam:4648): WARNING **: Could not initialize NMClient /org/freedesktop/NetworkManager: The name org.freedesktop.NetworkManager was not provided by any .service files

** (steam:4648): WARNING **: _nm_remote_settings_ensure_inited: (NMRemoteSettings) error initializing: The name org.freedesktop.NetworkManager was not provided by any .service files

Installing breakpad exception handler for appid(steam)/version(1393366296_client)
Installing breakpad exception handler for appid(steam)/version(1393366296_client)
PulseAudio connect failed (used only for Mic Volume Control) with error: Access denied
Installing breakpad exception handler for appid(steam)/version(1393366296_client)
Installing breakpad exception handler for appid(steam)/version(1393366296_client)
Generating new string page texture 2: 48x256, total string texture memory is 49,15 KB
Generating new string page texture 3: 256x256, total string texture memory is 311,30 KB
Installing breakpad exception handler for appid(steam)/version(1393366296_client)
Installing breakpad exception handler for appid(steam)/version(1393366296_client)
Adding licenses for the following package(s): 0, 20, 2294, 7930, 11829, 12361, 13314, 15609, 16549, 17915, 17941, 32749, 38900
roaming config store loaded successfully - 2708 bytes.
migrating temporary roaming config store
Installing breakpad exception handler for appid(steam)/version(1393366296_client)
ExecCommandLine: "/home/lampus/.local/share/Steam/ubuntu12_32/steam"
System startup time: 16,00 seconds
Installing breakpad exception handler for appid(steam)/version(1393366296_client)
OnFocusWindowChanged to window type: k_EWindowTypeSteamDesktop, 0
Running Steam on arch  64-bit
STEAM_RUNTIME has been set by the user to: /home/lampus/.local/share/Steam/ubuntu12_32/steam-runtime
Generating new string page texture 72: 1024x256, total string texture memory is 1,36 MB
Generating new string page texture 73: 256x256, total string texture memory is 262,14 KB
Generating new string page texture 74: 128x256, total string texture memory is 1,49 MB
Generating new string page texture 75: 32x256, total string texture memory is 1,52 MB
Generating new string page texture 76: 64x256, total string texture memory is 1,59 MB
ExecCommandLine: "/home/lampus/.steam/root/ubuntu12_32/steam steam://open/driverhelperready"
ExecSteamURL: "steam://open/driverhelperready"
Generating new string page texture 80: 256x256, total string texture memory is 1,85 MB
Generating new string page texture 81: 128x256, total string texture memory is 1,98 MB
Generating new string page texture 83: 256x256, total string texture memory is 2,24 MB
Generating new string page texture 86: 384x256, total string texture memory is 2,64 MB
Generating new string page texture 87: 8x256, total string texture memory is 2,65 MB
Installing breakpad exception handler for appid(steam)/version(1393366296_client)
Installing breakpad exception handler for appid(steam)/version(1393366296_client)
Installing breakpad exception handler for appid(steam)/version(1393366296_client)
Generating new string page texture 124: 128x256, total string texture memory is 2,78 MB
Game update: AppID 620 "Portal 2 (Beta)", ProcID 4732, IP 0.0.0.0:0
ERROR: ld.so: object '/home/lampus/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
CGameStreamThread: Added instance ID 4732 for appid 620
CGameStreamThread: Set render instance ID 4732 for appid 620

(steam:4648): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4648): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4648): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4648): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4648): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4648): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4648): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4648): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4648): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4648): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4648): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4648): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4648): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4648): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4648): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4648): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4648): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4648): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4648): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4648): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4648): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4648): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
ERROR: ld.so: object '/home/lampus/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
pid 4734 != 4733, skipping destruction (fork without exec?)
ERROR: ld.so: object '/home/lampus/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/lampus/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
CGameStreamThread: Added instance ID 4733 for appid 620
ERROR: ld.so: object '/home/lampus/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
gdb: Symbol `acs_map' has different size in shared object, consider re-linking
CGameStreamThread: Added instance ID 4735 for appid 620
GNU gdb (GDB) 7.7
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-unknown-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/lampus/.local/share/Steam/SteamApps/common/Portal 2/portal2_linux...(no debugging symbols found)...done.
ERROR: ld.so: object '/home/lampus/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
warning: Could not load shared library symbols for linux-gate.so.1.
Do you need "set solib-search-path" or "set sysroot"?
ERROR: ld.so: object '/home/lampus/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
CGameStreamThread: Added instance ID 4736 for appid 620
CGameStreamThread: Added instance ID 4737 for appid 620
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
CGameStreamThread: Added instance ID 4738 for appid 620
[New Thread 0xf3ce8b40 (LWP 4743)]
[New Thread 0xf3be7b40 (LWP 4744)]
[New Thread 0xf3ae6b40 (LWP 4745)]
[New Thread 0xf39e5b40 (LWP 4746)]
[New Thread 0xf38e4b40 (LWP 4747)]
[New Thread 0xf37e3b40 (LWP 4748)]
[New Thread 0xf36e2b40 (LWP 4749)]
[New Thread 0xf35e1b40 (LWP 4750)]
CGameStreamThread: Added instance ID 4739 for appid 620
SDL video target is 'x11'

SDL failed to create GL compatibility profile (whichProfile=0!

CGameStreamThread: Set render instance ID 4739 for appid 620
Installing breakpad exception handler for appid(gameoverlayui)/version(20140225134510_client)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0_client)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0_client)
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number

(gameoverlayui:4751): Gtk-WARNING **: Загружаемый модуль тем не найден в module_path: «oxygen-gtk»,

(gameoverlayui:4751): Gtk-WARNING **: Загружаемый модуль тем не найден в module_path: «oxygen-gtk»,
[0226/170009:ERROR:object_proxy.cc(239)] Failed to call method: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.NetworkManager was not provided by any .service files
[0226/170009:WARNING:proxy_service.cc(958)] PAC support disabled because there is no system implementation
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0_client)
Setting breakpad minidump AppID = 620
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561197999188111 [API loaded no]
Did not detect any valid joysticks.

CSoundEmitterSystemBase::BaseInit:  Manifest 'scripts/game_sounds_manifest.txt' with bogus file type 'new_sound_scripts_must_go_below_here', expecting 'declare_file' or 'precache_file'

Convar r_flashlightscissor has conflicting FCVAR_CHEAT flags (child: no FCVAR_CHEAT, parent: has FCVAR_CHEAT, parent wins)

OnFocusWindowChanged to window type: k_EWindowTypeNonSteamDesktop, 0
[New Thread 0xf3321b40 (LWP 4761)]
SDL video target is 'x11'
SDL failed to create GL compatibility profile (whichProfile=0!
This system supports the OpenGL extension GL_EXT_framebuffer_object.
This system supports the OpenGL extension GL_EXT_framebuffer_blit.
This system supports the OpenGL extension GL_EXT_framebuffer_multisample.
This system DOES NOT support the OpenGL extension GL_APPLE_fence.
This system supports the OpenGL extension GL_NV_fence.
This system supports the OpenGL extension GL_ARB_sync.
This system supports the OpenGL extension GL_EXT_draw_buffers2.
This system supports the OpenGL extension GL_EXT_bindable_uniform.
This system DOES NOT support the OpenGL extension GL_APPLE_flush_buffer_range.
This system supports the OpenGL extension GL_ARB_map_buffer_range.
This system supports the OpenGL extension GL_ARB_vertex_buffer_object.
This system supports the OpenGL extension GL_ARB_occlusion_query.
This system DOES NOT support the OpenGL extension GL_APPLE_texture_range.
This system DOES NOT support the OpenGL extension GL_APPLE_client_storage.
This system DOES NOT support the OpenGL extension GL_ARB_uniform_buffer.
This system supports the OpenGL extension GL_ARB_vertex_array_bgra.
This system supports the OpenGL extension GL_EXT_vertex_array_bgra.
This system supports the OpenGL extension GL_ARB_framebuffer_object.
This system DOES NOT support the OpenGL extension GL_GREMEDY_string_marker.
This system supports the OpenGL extension GL_ARB_debug_output.
This system supports the OpenGL extension GL_EXT_direct_state_access.
This system DOES NOT support the OpenGL extension GL_NV_bindless_texture.
This system DOES NOT support the OpenGL extension GL_AMD_pinned_memory.
This system supports the OpenGL extension GL_EXT_framebuffer_multisample_blit_scaled.
This system supports the OpenGL extension GL_EXT_texture_sRGB_decode.
This system supports the OpenGL extension GL_NVX_gpu_memory_info.
This system DOES NOT support the OpenGL extension GL_ATI_meminfo.
This system supports the OpenGL extension GL_EXT_texture_compression_s3tc.
This system supports the OpenGL extension GL_EXT_texture_compression_dxt1.
This system DOES NOT support the OpenGL extension GL_ANGLE_texture_compression_dxt3.
This system DOES NOT support the OpenGL extension GL_ANGLE_texture_compression_dxt5.
This system supports the OpenGL extension GLX_EXT_swap_control_tear.
Did not detect any valid joysticks.
CSoundEmitterSystemBase::BaseInit:  Manifest 'scripts/game_sounds_manifest.txt' with bogus file type 'new_sound_scripts_must_go_below_here', expecting 'declare_file' or 'precache_file'
Convar r_flashlightscissor has conflicting FCVAR_CHEAT flags (child: no FCVAR_CHEAT, parent: has FCVAR_CHEAT, parent wins)

 ##### swap interval = -1     swap limit = 1 #####
OnFocusWindowChanged to window type: k_EWindowTypeGame, 620
[New Thread 0xefb20b40 (LWP 4762)]
[New Thread 0xef31fb40 (LWP 4763)]
[Thread 0xef31fb40 (LWP 4763) exited]
CClientSteamContext logged on = 1

Convar building_cubemaps has conflicting FCVAR_CHEAT flags (child: has FCVAR_CHEAT, parent: no FCVAR_CHEAT, parent wins)

Game.dll loaded for "Half-Life 2"

Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
[New Thread 0xebbc6b40 (LWP 4764)]
[Thread 0xebbc6b40 (LWP 4764) exited]
[New Thread 0xebac5b40 (LWP 4765)]
[New Thread 0xeb9c4b40 (LWP 4766)]
[New Thread 0xeb8c3b40 (LWP 4767)]
[New Thread 0xeb7c2b40 (LWP 4768)]
Installing breakpad exception handler for appid(steam)/version(1393366296_client)
[New Thread 0xeadeab40 (LWP 4770)]
[New Thread 0xea854b40 (LWP 4773)]
[New Thread 0xea6e4b40 (LWP 4774)]
ALSA lib pcm.c:7339:(snd_pcm_recover) underrun occurred
[Thread 0xea854b40 (LWP 4773) exited]
[New Thread 0xea854b40 (LWP 4775)]
[New Thread 0xeeb17b40 (LWP 4776)]

Program received signal SIGSEGV, Segmentation fault.
0xf6dfe554 in ?? () from /usr/lib32/libnvidia-glcore.so.331.38
Argument list to give program being debugged when it is started is "-game portal2 -steam".
(gdb) OnFocusWindowChanged to window type: k_EWindowTypeSteamDesktop, 0
OnFocusWindowChanged to window type: k_EWindowTypeGame, 620

(gdb) bt
#0  0xf6dfe554 in ?? () from /usr/lib32/libnvidia-glcore.so.331.38
#1  0xf6e55084 in ?? () from /usr/lib32/libnvidia-glcore.so.331.38
#2  0xf6e42356 in ?? () from /usr/lib32/libnvidia-glcore.so.331.38
#3  0xf6ab8179 in ?? () from /usr/lib32/libnvidia-glcore.so.331.38
#4  0xf3eb452b in IDirect3DDevice9::DrawIndexedPrimitive(_D3DPRIMITIVETYPE, int, unsigned int, unsigned int, unsigned int, unsigned int) ()
   from /home/lampus/.local/share/Steam/SteamApps/common/Portal 2/bin/libtogl.so
#5  0xf1216fa6 in ?? () from /home/lampus/.local/share/Steam/SteamApps/common/Portal 2/bin/shaderapidx9.so
#6  0xf122d772 in ?? () from /home/lampus/.local/share/Steam/SteamApps/common/Portal 2/bin/shaderapidx9.so
#7  0xf2094890 in ?? () from /home/lampus/.local/share/Steam/SteamApps/common/Portal 2/bin/materialsystem.so
#8  0xefe1792a in ?? () from /home/lampus/.local/share/Steam/SteamApps/common/Portal 2/bin/stdshader_dx9.so
#9  0xefdee3e4 in ?? () from /home/lampus/.local/share/Steam/SteamApps/common/Portal 2/bin/stdshader_dx9.so
#10 0xefde99f7 in ?? () from /home/lampus/.local/share/Steam/SteamApps/common/Portal 2/bin/stdshader_dx9.so
#11 0xefe17594 in ?? () from /home/lampus/.local/share/Steam/SteamApps/common/Portal 2/bin/stdshader_dx9.so
#12 0xf2095c52 in ?? () from /home/lampus/.local/share/Steam/SteamApps/common/Portal 2/bin/materialsystem.so
#13 0xf2038dd2 in ?? () from /home/lampus/.local/share/Steam/SteamApps/common/Portal 2/bin/materialsystem.so
#14 0xf1230774 in ?? () from /home/lampus/.local/share/Steam/SteamApps/common/Portal 2/bin/shaderapidx9.so
#15 0xf1213709 in ?? () from /home/lampus/.local/share/Steam/SteamApps/common/Portal 2/bin/shaderapidx9.so
#16 0xf1213967 in ?? () from /home/lampus/.local/share/Steam/SteamApps/common/Portal 2/bin/shaderapidx9.so
#17 0xf209a2a4 in ?? () from /home/lampus/.local/share/Steam/SteamApps/common/Portal 2/bin/materialsystem.so
#18 0xf209aef8 in ?? () from /home/lampus/.local/share/Steam/SteamApps/common/Portal 2/bin/materialsystem.so
#19 0xed46e6a9 in ?? () from /home/lampus/.local/share/Steam/SteamApps/common/Portal 2/portal2/bin/client.so
#20 0xed3d74ed in ?? () from /home/lampus/.local/share/Steam/SteamApps/common/Portal 2/portal2/bin/client.so
#21 0xed4ea0b8 in ?? () from /home/lampus/.local/share/Steam/SteamApps/common/Portal 2/portal2/bin/client.so
#22 0xf26c55bf in ?? () from /home/lampus/.local/share/Steam/SteamApps/common/Portal 2/bin/engine.so
#23 0xf268cf37 in ?? () from /home/lampus/.local/share/Steam/SteamApps/common/Portal 2/bin/engine.so
#24 0xf25b2e68 in ?? () from /home/lampus/.local/share/Steam/SteamApps/common/Portal 2/bin/engine.so
#25 0xf281543b in ?? () from /home/lampus/.local/share/Steam/SteamApps/common/Portal 2/bin/engine.so
#26 0xf28157e2 in ?? () from /home/lampus/.local/share/Steam/SteamApps/common/Portal 2/bin/engine.so
#27 0xf28158db in ?? () from /home/lampus/.local/share/Steam/SteamApps/common/Portal 2/bin/engine.so
#28 0xf2816198 in ?? () from /home/lampus/.local/share/Steam/SteamApps/common/Portal 2/bin/engine.so
#29 0xf282c47e in ?? () from /home/lampus/.local/share/Steam/SteamApps/common/Portal 2/bin/engine.so
#30 0xf26ed4b3 in ?? () from /home/lampus/.local/share/Steam/SteamApps/common/Portal 2/bin/engine.so
#31 0xf27b6f76 in ?? () from /home/lampus/.local/share/Steam/SteamApps/common/Portal 2/bin/engine.so
#32 0xf27b8c0c in ?? () from /home/lampus/.local/share/Steam/SteamApps/common/Portal 2/bin/engine.so
#33 0xf27d169e in ?? () from /home/lampus/.local/share/Steam/SteamApps/common/Portal 2/bin/engine.so
#34 0xf27d197a in ?? () from /home/lampus/.local/share/Steam/SteamApps/common/Portal 2/bin/engine.so
#35 0xf27d1a59 in ?? () from /home/lampus/.local/share/Steam/SteamApps/common/Portal 2/bin/engine.so
#36 0xf28b3a73 in ?? () from /home/lampus/.local/share/Steam/SteamApps/common/Portal 2/bin/engine.so
#37 0xf28b02dd in ?? () from /home/lampus/.local/share/Steam/SteamApps/common/Portal 2/bin/engine.so
#38 0xf28b03fd in ?? () from /home/lampus/.local/share/Steam/SteamApps/common/Portal 2/bin/engine.so
#39 0xf291c6f0 in ?? () from /home/lampus/.local/share/Steam/SteamApps/common/Portal 2/bin/engine.so
#40 0xf28b18cf in ?? () from /home/lampus/.local/share/Steam/SteamApps/common/Portal 2/bin/engine.so
#41 0xf443c8e0 in ?? () from bin/launcher.so
#42 0xf443c8e0 in ?? () from bin/launcher.so
#43 0xf4420363 in LauncherMain () from bin/launcher.so
#44 0x08048564 in main ()
(gdb) OnFocusWindowChanged to window type: k_EWindowTypeSteamDesktop, 0
OnFocusWindowChanged to window type: k_EWindowTypeGame, 620
Installing breakpad exception handler for appid(steam)/version(1393366296_client)
Installing breakpad exception handler for appid(steam)/version(1393366296_client)
OnFocusWindowChanged to window type: k_EWindowTypeSteamDesktop, 0
Generating new string page texture 127: 128x256, total string texture memory is 393,22 KB
Generating new string page texture 128: 64x256, total string texture memory is 2,84 MB
Generating new string page texture 129: 256x256, total string texture memory is 3,10 MB
sh: lsb_release: команда не найдена
Generating new string page texture 130: 128x256, total string texture memory is 3,24 MB
Generating new string page texture 132: 24x256, total string texture memory is 3,26 MB

(process:4824): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed
OnFocusWindowChanged to window type: k_EWindowTypeGame, 620
Generating new string page texture 135: 256x256, total string texture memory is 3,52 MB
OnFocusWindowChanged to window type: k_EWindowTypeSteamDesktop, 0
OnFocusWindowChanged to window type: k_EWindowTypeGame, 620

```

**Comment by timjp87** [comment]
You basically hit F6 everytime before you enter the elevator? I did this for a couple of test chambers in a row without issues and I have a similar system. http://pastebin.com/VynD0zmx

Something else might trigger this.

**Comment by Lampus** [comment]
I don't hit F6 everytime, I did it only for demonstration. I mean, that crash occurs only on second stage load.
And we have different versions of NVidia driver (331.38 in my case vs. 334.16).
But as you can see in GDB backtrace, segfault occurs in function that calls something in /usr/lib32/libnvidia-glcore.so.331.38

**Comment by Lampus** [comment]
Same problem with updated NVidia driver was observed (334.16):

```
(gdb) bt
#0  0xf6d80a5b in ?? () from /usr/lib32/libnvidia-glcore.so.334.16
#1  0xf6dd7238 in ?? () from /usr/lib32/libnvidia-glcore.so.334.16
#2  0xf6dc44c6 in ?? () from /usr/lib32/libnvidia-glcore.so.334.16
#3  0xf6a3aa39 in ?? () from /usr/lib32/libnvidia-glcore.so.334.16
#4  0xf3dc252b in IDirect3DDevice9::DrawIndexedPrimitive(_D3DPRIMITIVETYPE, int, unsigned int, unsigned int, unsigned int, unsigned int) ()
   from /home/lampus/.local/share/Steam/SteamApps/common/Portal 2/bin/libtogl.so
#5  0xf1122fa6 in ?? () from /home/lampus/.local/share/Steam/SteamApps/common/Portal 2/bin/shaderapidx9.so
#6  0xf1139772 in ?? () from /home/lampus/.local/share/Steam/SteamApps/common/Portal 2/bin/shaderapidx9.so
#7  0xf1fa0890 in ?? () from /home/lampus/.local/share/Steam/SteamApps/common/Portal 2/bin/materialsystem.so
#8  0xefd2392a in ?? () from /home/lampus/.local/share/Steam/SteamApps/common/Portal 2/bin/stdshader_dx9.so
#9  0xefcfa3e4 in ?? () from /home/lampus/.local/share/Steam/SteamApps/common/Portal 2/bin/stdshader_dx9.so
#10 0xefcf59f7 in ?? () from /home/lampus/.local/share/Steam/SteamApps/common/Portal 2/bin/stdshader_dx9.so
#11 0xefd23594 in ?? () from /home/lampus/.local/share/Steam/SteamApps/common/Portal 2/bin/stdshader_dx9.so
#12 0xf1fa1c52 in ?? () from /home/lampus/.local/share/Steam/SteamApps/common/Portal 2/bin/materialsystem.so
#13 0xf1f44dd2 in ?? () from /home/lampus/.local/share/Steam/SteamApps/common/Portal 2/bin/materialsystem.so
#14 0xf113c774 in ?? () from /home/lampus/.local/share/Steam/SteamApps/common/Portal 2/bin/shaderapidx9.so
#15 0xf111f709 in ?? () from /home/lampus/.local/share/Steam/SteamApps/common/Portal 2/bin/shaderapidx9.so
#16 0xf111f967 in ?? () from /home/lampus/.local/share/Steam/SteamApps/common/Portal 2/bin/shaderapidx9.so
#17 0xf1fa62a4 in ?? () from /home/lampus/.local/share/Steam/SteamApps/common/Portal 2/bin/materialsystem.so
#18 0xf1fa6ef8 in ?? () from /home/lampus/.local/share/Steam/SteamApps/common/Portal 2/bin/materialsystem.so
#19 0xf25d0a5d in ?? () from /home/lampus/.local/share/Steam/SteamApps/common/Portal 2/bin/engine.so
#20 0xf25d0fe4 in ?? () from /home/lampus/.local/share/Steam/SteamApps/common/Portal 2/bin/engine.so
#21 0xf26c2f83 in ?? () from /home/lampus/.local/share/Steam/SteamApps/common/Portal 2/bin/engine.so
#22 0xf26c4c0c in ?? () from /home/lampus/.local/share/Steam/SteamApps/common/Portal 2/bin/engine.so
#23 0xf26dd69e in ?? () from /home/lampus/.local/share/Steam/SteamApps/common/Portal 2/bin/engine.so
#24 0xf26dd97a in ?? () from /home/lampus/.local/share/Steam/SteamApps/common/Portal 2/bin/engine.so
#25 0xf26dda59 in ?? () from /home/lampus/.local/share/Steam/SteamApps/common/Portal 2/bin/engine.so
#26 0xf27bfa73 in ?? () from /home/lampus/.local/share/Steam/SteamApps/common/Portal 2/bin/engine.so
#27 0xf27bc2dd in ?? () from /home/lampus/.local/share/Steam/SteamApps/common/Portal 2/bin/engine.so
#28 0xf27bc3fd in ?? () from /home/lampus/.local/share/Steam/SteamApps/common/Portal 2/bin/engine.so
#29 0xf28286f0 in ?? () from /home/lampus/.local/share/Steam/SteamApps/common/Portal 2/bin/engine.so
#30 0xf27bd8cf in ?? () from /home/lampus/.local/share/Steam/SteamApps/common/Portal 2/bin/engine.so
#31 0xf434a8e0 in ?? () from bin/launcher.so
#32 0xf434a8e0 in ?? () from bin/launcher.so
#33 0xf432e363 in LauncherMain () from bin/launcher.so
#34 0x08048564 in main ()
```

**Comment by ghost** [comment]
i have same error and same logs!

**Comment by Lampus** [comment]
I have found simple workaround for my case: change setting of shaders quality in advanced video options to low (I decided to try play with this option because of library name "_shader_apidx9.so" ).
Strange, but now game doesn't crash.

**Comment by timjp87** [comment]
I have the game completely maxed out on "Very High" shader level etc. and no crashes. Strange.

**Comment by bespokebob** [comment]
Originally posted this on issue #4, but my backtrace looks like yours:
https://gist.github.com/youngbob/6bf80c5fe4a95490ebfb

**Comment by bespokebob** [comment]
I played through the entire game with shaders on Low, with zero crashes. Started a new game with shaders set to Very High, and the game crashed on the second level load (right after "cube and button"). Lowered settings to High, and I have been able to load several levels in a row. I still can't get very far with settings on High, due to issue #51

**Comment by bespokebob** [comment]
Scratch that, I got a crash on High settings after GLaDOS dropped me into the incinerator. I have two crash IDs now. I don't think the game was generating crash dumps before.

Sun Mar  9 19:34:48 2014 GMT: file ''/tmp/dumps/crash_20140309152153_1.dmp'', upload yes: ''CrashID=bp-43397100-e870-4039-9cd8-96b5c2140309''
Sun Mar  9 20:05:47 2014 GMT: file ''/tmp/dumps/crash_20140309155459_1.dmp'', upload yes: ''CrashID=bp-38cac6c7-2172-4232-a8f7-a26d72140309''

**Comment by origintopleft** [comment]
It's not shaders - I have everything set to ultra-low (shaders included) and I still get crashes

**Comment by tbialas** [comment]
Crashed for me, i'm running Debian sid with NVidia 339.41

GNU gdb (GDB) 7.6.2 (Debian 7.6.2-1)
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later http://gnu.org/licenses/gpl.html
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
For bug reporting instructions, please see:
http://www.gnu.org/software/gdb/bugs/...
Reading symbols from /home/tbialas/.local/share/Steam/SteamApps/common/Portal 2/portal2_linux...(no debugging symbols found)...done.
warning: Could not load shared library symbols for linux-gate.so.1.
Do you need "set solib-search-path" or "set sysroot"?
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0xf750ab40 (LWP 1128)]
[New Thread 0xf7409b40 (LWP 1129)]
SDL video target is 'x11'

SDL failed to create GL compatibility profile (whichProfile=0!

Using breakpad crash handler
Setting breakpad minidump AppID = 620
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198079293222 [API loaded yes]
Steam_SetMinidumpSteamID:  Setting Steam ID:  76561198079293222
Did not detect any valid joysticks.

CSoundEmitterSystemBase::BaseInit:  Manifest 'scripts/game_sounds_manifest.txt' with bogus file type 'new_sound_scripts_must_go_below_here', expecting 'declare_file' or 'precache_file'

Convar r_flashlightscissor has conflicting FCVAR_CHEAT flags (child: no FCVAR_CHEAT, parent: has FCVAR_CHEAT, parent wins)

[New Thread 0xf302fb40 (LWP 1130)]
SDL video target is 'x11'
SDL failed to create GL compatibility profile (whichProfile=0!
This system supports the OpenGL extension GL_EXT_framebuffer_object.
This system supports the OpenGL extension GL_EXT_framebuffer_blit.
This system supports the OpenGL extension GL_EXT_framebuffer_multisample.
This system DOES NOT support the OpenGL extension GL_APPLE_fence.
This system supports the OpenGL extension GL_NV_fence.
This system supports the OpenGL extension GL_ARB_sync.
This system supports the OpenGL extension GL_EXT_draw_buffers2.
This system supports the OpenGL extension GL_EXT_bindable_uniform.
This system DOES NOT support the OpenGL extension GL_APPLE_flush_buffer_range.
This system supports the OpenGL extension GL_ARB_map_buffer_range.
This system supports the OpenGL extension GL_ARB_vertex_buffer_object.
This system supports the OpenGL extension GL_ARB_occlusion_query.
This system DOES NOT support the OpenGL extension GL_APPLE_texture_range.
This system DOES NOT support the OpenGL extension GL_APPLE_client_storage.
This system DOES NOT support the OpenGL extension GL_ARB_uniform_buffer.
This system supports the OpenGL extension GL_ARB_vertex_array_bgra.
This system supports the OpenGL extension GL_EXT_vertex_array_bgra.
This system supports the OpenGL extension GL_ARB_framebuffer_object.
This system DOES NOT support the OpenGL extension GL_GREMEDY_string_marker.
This system supports the OpenGL extension GL_ARB_debug_output.
This system supports the OpenGL extension GL_EXT_direct_state_access.
This system DOES NOT support the OpenGL extension GL_NV_bindless_texture.
This system DOES NOT support the OpenGL extension GL_AMD_pinned_memory.
This system supports the OpenGL extension GL_EXT_framebuffer_multisample_blit_scaled.
This system supports the OpenGL extension GL_EXT_texture_sRGB_decode.
This system supports the OpenGL extension GL_NVX_gpu_memory_info.
This system DOES NOT support the OpenGL extension GL_ATI_meminfo.
This system supports the OpenGL extension GL_EXT_texture_compression_s3tc.
This system supports the OpenGL extension GL_EXT_texture_compression_dxt1.
This system DOES NOT support the OpenGL extension GL_ANGLE_texture_compression_dxt3.
This system DOES NOT support the OpenGL extension GL_ANGLE_texture_compression_dxt5.
This system supports the OpenGL extension GLX_EXT_swap_control_tear.
Did not detect any valid joysticks.
CSoundEmitterSystemBase::BaseInit:  Manifest 'scripts/game_sounds_manifest.txt' with bogus file type 'new_sound_scripts_must_go_below_here', expecting 'declare_file' or 'precache_file'
Convar r_flashlightscissor has conflicting FCVAR_CHEAT flags (child: no FCVAR_CHEAT, parent: has FCVAR_CHEAT, parent wins)

 ##### swap interval = -1     swap limit = 1 #####
[New Thread 0xed448b40 (LWP 1131)]
[Thread 0xed448b40 (LWP 1131) exited]
[New Thread 0xed448b40 (LWP 1132)]
[New Thread 0xf17f2b40 (LWP 1133)]
[Thread 0xf17f2b40 (LWP 1133) exited]
CClientSteamContext logged on = 1

Convar building_cubemaps has conflicting FCVAR_CHEAT flags (child: has FCVAR_CHEAT, parent: no FCVAR_CHEAT, parent wins)

Game.dll loaded for "Half-Life 2"

[New Thread 0xe946cb40 (LWP 1135)]
[New Thread 0xe936bb40 (LWP 1136)]
[Thread 0xe946cb40 (LWP 1135) exited]
[New Thread 0xe926ab40 (LWP 1137)]
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198079293222 [API loaded yes]
Steam_SetMinidumpSteamID:  Setting Steam ID:  76561198079293222
[New Thread 0xe8915b40 (LWP 1139)]
[New Thread 0xe877eb40 (LWP 1143)]
[New Thread 0xe867db40 (LWP 1144)]
[Thread 0xe877eb40 (LWP 1143) exited]
[New Thread 0xe877eb40 (LWP 1145)]
[New Thread 0xec447b40 (LWP 1146)]
[New Thread 0xe8c22b40 (LWP 1147)]
[New Thread 0xe8b21b40 (LWP 1148)]
[New Thread 0xe7d7cb40 (LWP 1149)]
[Thread 0xe8c22b40 (LWP 1147) exited]
[Thread 0xe8b21b40 (LWP 1148) exited]
[Thread 0xe7d7cb40 (LWP 1149) exited]
[New Thread 0xe7d7cb40 (LWP 1150)]
[New Thread 0xe8b21b40 (LWP 1151)]
[New Thread 0xe8c22b40 (LWP 1152)]
[New Thread 0xec7c7b40 (LWP 1153)]
[Thread 0xe8b21b40 (LWP 1151) exited]
[Thread 0xe8c22b40 (LWP 1152) exited]
[Thread 0xec7c7b40 (LWP 1153) exited]
[New Thread 0xec7c7b40 (LWP 1163)]
[New Thread 0xe8c22b40 (LWP 1164)]
[New Thread 0xe8b21b40 (LWP 1165)]
[Thread 0xec7c7b40 (LWP 1163) exited]
[Thread 0xe8c22b40 (LWP 1164) exited]
[Thread 0xe8b21b40 (LWP 1165) exited]

Program received signal SIGSEGV, Segmentation fault.
0xf62b0d54 in ?? () from /usr/lib/i386-linux-gnu/libnvidia-glcore.so.331.49
Argument list to give program being debugged when it is started is "-game portal2 -steam".

**Comment by tbialas** [comment]
We can assume this is related to the NVidia driver (libnvidia-glcore.so.<version>)

**Comment by tbialas** [comment]
The issue seems to have been solved with Nvidia 331.67-1 on Debian testing/unstable.
The package is available in the unstable repo, you can upgrade with apt-get install -t unstable nvidia-driver

**Comment by origintopleft** [comment]
Problem appears to have gone away for me too, Gentoo Linux with NVidia drivers 337.12.

Incidentally, the -1 at the end of that version tbx1024 posted suggests Debian (somehow) tinkered with it, maybe it's unrelated, but if your distro's latest drivers (even on any unstable channels) don't seem to be doing the trick, try grabbing the package directly from NVidia's website.

**Comment by kisak-valve** [comment]
Hello, is anyone still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing as outdated.
